### ISSUE TITLE
some system tests failing 

### ISSUE THREAD

**Issue by jedwards4b** [bandre-ucar/manage_externals#202]
### Expected behavior and actual behavior:
test_submodule_checkout_bare
test_submodule_checkout_config
test_submodule_checkout_none

All use git submodule add of a file:/// type submodule.
This results in
 fatal: transport 'file' not allowed
due to https://github.blog/2022-10-18-git-security-vulnerabilities-announced/

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository): 
Using git 2.39.0 or newer run make stest in the test directory.

### Screen output or log file showing the error message and context:
```
PYTHONPATH=..: python -m unittest discover --buffer --pattern 'test_sys_*.py'
EEE.....................................
======================================================================
ERROR: test_submodule_checkout_bare (test_sys_checkout.TestSubrepoCheckout)
Verify that a git repo with submodule is properly checked out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 257, in execute_subprocess
    output = subprocess.check_output(commands, stderr=subprocess.STDOUT,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'submodule', 'add', '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/test_sys_checkout.py", line 1561, in setUp
    execute_subprocess(cmd)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 287, in execute_subprocess
    fatal_error(msg)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 109, in fatal_error
    raise RuntimeError("{0}ERROR: {1}".format(os.linesep, message))
RuntimeError: 
ERROR: Failed with output:
    Cloning into '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_bare/test_repo_with_submodules/simple-ext-fork'...
    fatal: transport 'file' not allowed
    fatal: clone of '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git' into submodule path '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_bare/test_repo_with_submodules/simple-ext-fork' failed

ERROR: In directory
    /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_bare/test_repo_with_submodules
Process did not run successfully; returned status 128:
    git submodule add /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git
See above for output from failed command.


======================================================================
ERROR: test_submodule_checkout_config (test_sys_checkout.TestSubrepoCheckout)
Verify that a git repo with submodule is properly checked out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 257, in execute_subprocess
    output = subprocess.check_output(commands, stderr=subprocess.STDOUT,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'submodule', 'add', '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/test_sys_checkout.py", line 1561, in setUp
    execute_subprocess(cmd)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 287, in execute_subprocess
    fatal_error(msg)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 109, in fatal_error
    raise RuntimeError("{0}ERROR: {1}".format(os.linesep, message))
RuntimeError: 
ERROR: Failed with output:
    Cloning into '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_config/test_repo_with_submodules/simple-ext-fork'...
    fatal: transport 'file' not allowed
    fatal: clone of '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git' into submodule path '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_config/test_repo_with_submodules/simple-ext-fork' failed

ERROR: In directory
    /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_config/test_repo_with_submodules
Process did not run successfully; returned status 128:
    git submodule add /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git
See above for output from failed command.


======================================================================
ERROR: test_submodule_checkout_none (test_sys_checkout.TestSubrepoCheckout)
Verify that a git repo with submodule is properly checked out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 257, in execute_subprocess
    output = subprocess.check_output(commands, stderr=subprocess.STDOUT,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/glade/u/apps/derecho/23.09/opt/._view/dbmk4spxf6a6cxbb2s5lhzfc7dtoyw3m/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'submodule', 'add', '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/test_sys_checkout.py", line 1561, in setUp
    execute_subprocess(cmd)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 287, in execute_subprocess
    fatal_error(msg)
  File "/glade/work/jedwards/sandboxes/jimmielin/manage_externals/manic/utils.py", line 109, in fatal_error
    raise RuntimeError("{0}ERROR: {1}".format(os.linesep, message))
RuntimeError: 
ERROR: Failed with output:
    Cloning into '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_none/test_repo_with_submodules/simple-ext-fork'...
    fatal: transport 'file' not allowed
    fatal: clone of '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git' into submodule path '/glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_none/test_repo_with_submodules/simple-ext-fork' failed

ERROR: In directory
    /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/tmp/test_submodule_checkout_none/test_repo_with_submodules
Process did not run successfully; returned status 128:
    git submodule add /glade/work/jedwards/sandboxes/jimmielin/manage_externals/test/repos/simple-ext-fork.git
See above for output from failed command.


----------------------------------------------------------------------
Ran 40 tests in 63.675s
```

FAILED (errors=3)
make: *** [Makefile:64: stest] Error 1

**Comment by ekluzek** [comment]
@jedwards4b thanks for filing this. I and Naoki just noticed it as well.

I think this is largely a symptom of not having a person dedicated to make sure manage_externals is maintained. You and others have volunteered to do PR's to fix issues which has been great.

The only idea I have is that maybe it would be worth it for CESM to have someone dedicate some time to fix these tests and also add some github actions to run periodic testing in this repo. The only idea I have for identifying the "someone" is to bring it up at a future CSEG meeting. Maybe we could get a volunteer, or at least authorize someone to spend the time on this. manage_externals is a backbone tool for CESM that we really need to maintain...
